### ISSUE TITLE
TypeError: Cannot read property 'setIcon' of undefined

### ISSUE THREAD

**Issue by rudyxu1102** [felixglow/ElectronProject#1]
### hello，博主，最近在学习electron，npm start后报错
```
App threw an error during load
TypeError: Cannot read property 'setIcon' of undefined
    at Object.<anonymous> (D:\graduation\ElectronProject\main.js:28:9)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at loadApplicationPackage (D:\graduation\ElectronProject\node_modules\_electron-prebuilt@1.4.13@electron-prebuilt\dist\resources\default_app.asar\main.js:280:12)
    at Object.<anonymous> (D:\graduation\ElectronProject\node_modules\_electron-prebuilt@1.4.13@electron-prebuilt\dist\resources\default_app.asar\main.js:322:5)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
```

git clone之后，  sqlite3 tchli.db，npm install，接着npm start，
是不是我缺了哪个步骤？win10系统，谢谢

**Comment by felixglow** [comment]
不好意思，最近比较忙没看邮件，之前我是在MacOS下开发的，你可以看下我博客中的简单教程，或许对你有帮助
https://www.felixglow.com/blog/35/
![image](https://user-images.githubusercontent.com/8147810/28497009-472b2912-6fae-11e7-8d43-36c626b5467e.png)
